# -*- coding: utf-8 -*-
"""HW3_SE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ddTdAO7MMX1PUhDMX06acNruxRW10gyf
"""

import json
#Make class 'Person'
class Person:

    #Initialize variables
    def __init__(self, username, password, age, address, wallet=0):
        self.username = username
        self.password = password
        self.age = age
        self.address = address
        self.wallet = wallet

    #Save to json file
    def save_to_file(self):
        with open(f'{self.username}.json', 'w') as file:
            json.dump(self.__dict__, file)

    #Update amount of wallet
    def update_wallet(self, amount):
        self.wallet += amount
        self.save_to_file()
        return f"New amount of wallet: {self.wallet}"

    #Update address with new ones
    def update_address(self, new_address):
        while True:
            if not new_address:
                print("Error: should not be empty")
            if "شهر" not in new_address and "shahr" not in new_address:
                print("Error: Enter shahr(شهر)")
            if "پلاک" not in new_address and "pelak" not in new_address:
                print("Error: Enter pelak(پلاک)")
            else:
                self.address = new_address
                self.save_to_file()
                return "New address saved"
            new_address = input("Enter new address: ")


#Login for entrance to account
def login(username, password):
    try:
        with open(f'{username}.json', 'r') as file:
            user_data = json.load(file)
            if user_data['password'] == password:
                return "Welcome " + username
            else:
                return "incorrect password"
    except FileNotFoundError:
        return "User not founded"

#Sign up if user has not account
def sign_up():
    username = input("Enter Username: ")
    password = input("Enter Password: ")
    age = input("Enter Age: ")
    address = input("Enter Address: ")
    new_user = Person(username, password, age, address)
    new_user.save_to_file()
    return "Congratulation, Account created"

#Run code
def main():
    choice = input("Login (L) or Sign Up (S)? ")
    #Login
    if choice.lower() == 'l':
        username = input("Enter Username: ")
        password = input("Enter Password: ")
        result = login(username, password)
        print(result)
        if result == "Welcome " + username :

          #Check for update address
          res1 = input('Do you want to change address?(Y/N)').lower()
          if res1 == 'y':

            file = open(f'{username}.json', 'r')
            user_data = json.load(file)
            username = user_data['username']
            password = user_data['password']
            age = user_data['age']
            address = user_data['address']
            wallet = user_data['wallet']
            person = Person(username, password, age, address, wallet)
            new_address = input("Enter new address: ")
            print(person.update_address(new_address))


          #Check for update wallet
          res2 = input('Do you prefer to charge your wallet?(Y/N)').lower()
          if res2 == 'y' :
            amount = eval(input('Amount of wallet: '))

            file =  open(f'{username}.json', 'r')
            user_data = json.load(file)
            username = user_data['username']
            password = user_data['password']
            age = user_data['age']
            address = user_data['address']
            wallet = user_data['wallet']
            person = Person(username, password, age, address, wallet)
            print(person.update_wallet(amount))


    #Sign up
    elif choice.lower() == 's':
        print(sign_up())
        print('If you want to login to your account, please run code again \nThanks')

if __name__ == "__main__":
    main()