# -*- coding: utf-8 -*-
"""Online_Store.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZeFCSyHGPWMoUnmrOGbUPguI_ENHEetE
"""

import csv

# Data structure to hold product information
products = {}
shopping_cart = []
user_wallet = 10000.00  # Example user wallet balance

# Read product data from the CSV file
def read_products(file_path):
    with open(file_path, mode='r') as file:
        csv_reader = csv.DictReader(file)
        for row in csv_reader:
            product_id = int(row['ID'])
            products[product_id] = {
                'name': row['Name'],
                'type': row['Type'],
                'price': float(row['Price']),
                'availability': row['Is_available'] == 'TRUE',
                'rating': float(row['Rate'])
            }

# Function to add product to the shopping cart
def add_product_to_cart(product_id):
    if not product_id.isnumeric():
      return "Error: Only enter numbers!"

    product_id = int(product_id)
    if product_id not in products:
      return "No product found!"

    product = products[product_id]
    if not product['availability']:
        return "The product is not available at the moment!"

    shopping_cart.append(product)
    return f"Added to cart: {product['name']} - {product['type']} - ${product['price']}"



# Function to process payment and display receipt
def process_payment():
    global user_wallet
    total_amount = sum(item['price'] for item in shopping_cart)

    if total_amount > user_wallet:
        print("Error: Not enough money!")
        return

    user_wallet -= total_amount
    print("Payment successful!")
    print("Receipt:")
    for item in shopping_cart:
        print(f"{item['name']} - {item['type']} - ${item['price']}")
    print(f"Total: ${total_amount}")
    print(f"Remaining wallet balance: ${user_wallet}")

# Read products from the provided CSV file
file_path = '/content/products.csv'
read_products(file_path)

# Example Usage
while True:
    print("\n1. Add product to cart")
    print("2. Checkout")
    print("3. Exit")
    choice = input("Enter your choice: ")

    if choice == '1':
        product_id = input("Enter product ID to add to cart: ")
        print(add_product_to_cart(product_id))
    elif choice == '2':
        process_payment()
        shopping_cart.clear()
    elif choice == '3':
        break
    else:
        print("Invalid choice. Please try again.")